"use client";

import type { Metadata } from "next";
import { Geist, Geist_Mono, Cairo } from "next/font/google";
import { Toaster as SonnerToaster } from "@/components/ui/sonner";
import "./globals.css";
import { ThemeProvider, useTheme } from "next-themes";
import { useAppSettingsStore } from "@/helpers/stores/settings.store";
import { useEffect, useTransition } from "react";
import TranslationsProvider from "@/helpers/i18n/translation.provider";
// import initTranslations, { i18nNamespaces } from "@/helpers/i18n/i18n";
import "@/helpers/i18n/i18n";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const cairoSans = Cairo({
  subsets: ["arabic", "latin"],
  variable: "--font-cairo",
});

// export const metadata: Metadata = {
//   title: "Article App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: any;
}>) {
  const { toggleLanguage, language, theme } = useAppSettingsStore();
  // const { theme: nextTheme, setTheme: setNextTheme } = useTheme();

  // useEffect(() => {
  //   setNextTheme(theme === "Dark" ? "dark" : "light");
  // }, [theme]);

  // var resources;
  // const locale = language === "English" ? "en" : "ar";
  // initTranslations(locale, i18nNamespaces).then((val) => (resources = val));

  return (
    <html suppressHydrationWarning>
      <body
        className={`
          ${cairoSans.variable}
          ${geistSans.variable}`}
        lang={language === "English" ? "en" : "ar"}
        dir={language === "English" ? "ltr" : "rtl"}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          // disableTransitionOnChange
        >
          <SonnerToaster
            toastOptions={{}}
            expand={false}
            position="bottom-right"
            closeButton
            richColors
            visibleToasts={4}
            duration={8000}
          />

          {children}
          {/* <TranslationsProvider
            namespaces={i18nNamespaces}
            locale={locale}
            resources={resources}
          >
            {children}
          </TranslationsProvider> */}
        </ThemeProvider>
      </body>
    </html>
  );
}
